#!/usr/bin/with-contenv bash

 echo "**** Creating CONFIG ****"

MQTT_HOST="$(jq --raw-output '.mqttHost' $CONFIG_PATH)"
MQTT_USER="$(jq --raw-output '.mqttUser' $CONFIG_PATH)"
MQTT_PASS="$(jq --raw-output '.mqttPassword' $CONFIG_PATH)"
AIRCONIP="$(jq --raw-output '.airConIp' $CONFIG_PATH)"
AIRCONMAC="$(jq --raw-output '.airConMac' $CONFIG_PATH)"
AIRCONPORT="$(jq --raw-output '.airConPort' $CONFIG_PATH)"
AIRCONNAME="$(jq --raw-output '.airConName' $CONFIG_PATH)"


cat > /config/config.yml << EOL
service:
    daemon_mode: True
    update_interval: 10
    self_discovery: True
    bind_to_ip: False

mqtt:
    host: ${MQTT_HOST}
    port: 1883
    client_id: ac_to_mqtt
    user: ${MQTT_USER}
    passwd: ${MQTT_PASS}
    topic_prefix: /aircon
    auto_discovery_topic: homeassistant
    auto_discovery_topic_retain: True
    discovery: True

##Devices
devices:
- ip: ${AIRCONIP}
  mac: ${AIRCONMAC}
  name: ${AIRCONNAME}
  port: ${AIRCONPORT}
EOL

# update app
currentVersion=$(cat /app/ac2mqtt/version.txt)
LATEST_RELEASE=$(curl -sX GET "https://api.github.com/repos/liaan/broadlink_ac_mqtt/releases/latest"  | jq -r '. | .tag_name')

if [ ${LATEST_RELEASE} != ${currentVersion} ]; then
   echo "**** Newer version found. Grabbing latest code ****"
   curl -o /tmp/ac2mqtt.tar.gz -L "https://github.com/liaan/broadlink_ac_mqtt/archive/${LATEST_RELEASE}.tar.gz"
   tar xf /tmp/ac2mqtt.tar.gz -C /app/ac2mqtt --strip-components=1
   # hard code version 
   echo "**** Updating versions ****"
   echo ${LATEST_RELEASE} > /app/ac2mqtt/version.txt
else
   echo "**** Already at latest version ****"
fi

cat /config/config.yml

# permissions
chown abc:abc -R \
	/config \
	/app